# Generated by Django 4.1.4 on 2022-12-19 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipments',
                'verbose_name_plural': 'Equipments',
                'db_table': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='Excercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('calories_burnt', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises_app.equipments')),
            ],
            options={
                'verbose_name': 'Excercises',
                'verbose_name_plural': 'Excercises',
                'db_table': 'excercises',
            },
        ),
    ]
