# Generated by Django 4.1.4 on 2022-12-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
